### ISSUE TITLE
CNCFSD-1106 Vitess website: search usability issues

### ISSUE THREAD

**Issue by nate-double-u** [cncf/techdocs#101]
https://cncfservicedesk.atlassian.net/browse/CNCFSD-1106

Related GH Issue: https://github.com/vitessio/website/issues/977

**Comment by deepthi** [comment]
How can we get this prioritized? Search on the vitess website is pretty much unusable right now.

**Comment by chalin** [comment]
I just posted a question which will help us clarify the amount of effort involved. For details, see: https://github.com/vitessio/website/issues/977#issuecomment-1110093831.

**Comment by nate-double-u** [comment]
related: https://github.com/vitessio/website/pull/1070

**Comment by nate-double-u** [comment]
closed with https://github.com/vitessio/website/pull/1119,
https://cncfservicedesk.atlassian.net/browse/CNCFSD-1106 set to resolved.

**Comment by chalin** [comment]
Woohoo! 🎉
