### ISSUE TITLE
Migrate CNCF websites to GA4

### ISSUE THREAD

**Issue by chalin** [cncf/techdocs#108]
[Deprecation notice from Google] (March 2022):

> Universal Analytics will no longer process new data in standard properties beginning July 1, 2023. Prepare now by setting up and switching over to a Google Analytics 4 property. [Learn more](https://support.google.com/analytics/answer/11583528)

We should migrate CNCF websites to GA4 as soon as possible so that by 2023Q3, when UA data collection stops, projects will already have 1+ year of historical data.

### Resources

- **[Migrating to Google Analytics 4]** details a suggested upgrade process.
  At a minimum we should implement **stage 1** for all CNCF projects ASAP.
- **Project migration [status spreadsheet]**

### Objectives

- OKR: https://github.com/cncf/workflow/issues/563
  - Note that some projects have multiple websites, which is why the number of sites to migrate increases over time as we report progress below.
- Complete the stage-1 migration of the top (velocity) 15 CNCF project websites by EOY 2022. Progress:
  - 33% (5/15) done as of 08/31
  - 60% (23/38) done as of 11/11
- Complete stage-2 & -3 migration for 30% or more of the top 15 CNCF project websites by EOY 2022. Progress:
  - 27% (4/15) done as of 08/31
  - 60% (23/38) done as of 11/11

---

### Pilot projects (and a few more)

For the **full migration-status** details, see the [status spreadsheet].

- [x] [kubernetes.io](http://kubernetes.io/) - https://github.com/kubernetes/website/issues/35299
- [x] [opentelemetry.io](https://opentelemetry.io/) - https://github.com/open-telemetry/opentelemetry.io/issues/1515
- [x] [Argo](https://argoproj.github.io/) - https://github.com/argoproj/argo-site/issues/102
- [x] backstage.io - https://github.com/backstage/backstage/issues/12658
- [x] [Prometheus.io](http://prometheus.io/) - https://github.com/prometheus/docs/issues/2181
- [x] gRPC.io - https://github.com/grpc/grpc.io/issues/1001
- [x] [envoyproxy.io](https://www.envoyproxy.io) - https://github.com/envoyproxy/envoy-website/issues/273
- [x] containerd.io - https://github.com/containerd/containerd.io/issues/131
- [x] etcd.io - https://github.com/etcd-io/website/issues/595
- [x] vitess.io - https://github.com/vitessio/website/issues/1098

Review:

- [x] For all projects using [Netlify snippet injection], ensure that the snippet is limited to production builds.

[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/
For a complete list of projects under migration, see the [status spreadsheet].

/cc @nate-double-u @caniszczyk

[connect]: https://support.google.com/analytics/answer/9973999
[opentelemetry.io/layouts/partials/google-analytics.html]: https://github.com/open-telemetry/opentelemetry.io/blob/3d8a59ea508b46497500297f334a079a4f91e293/layouts/partials/google-analytics.html
[status spreadsheet]: https://docs.google.com/spreadsheets/d/1Mx4LhdI2Un-rvGMI73SlHxQH9D2HABAJclMB3dd6lnA
[Deprecation notice from Google]: https://support.google.com/analytics/answer/11583528
[Migrating to Google Analytics 4]: https://github.com/cncf/techdocs/blob/main/docs/analytics.md#migrating-to-google-analytics-4

**Comment by chalin** [comment]
@caniszczyk - might it make sense to consider a CLOMonitor check for this?

**Comment by chalin** [comment]
Related: #105

**Comment by chalin** [comment]
Hey all, the GA4 dashboard isn't very intuitive IMHO. For example, I haven't yet found a way to define a report (that can be saved) for 404 pages. Maybe we should have a short meeting to share our collective experiences along with any resources we have found useful up until now?

/cc @thisisobate

**Comment by thisisobate** [comment]
Yes! @chalin 
That would be great!

**Comment by chalin** [comment]
All: FYI, here's a first try at this:

- https://github.com/open-telemetry/opentelemetry.io/issues/1515

I'll be looking at streamlining the process and looking into using Hugo's support for GA.

**Comment by chalin** [comment]
I'm wondering whether we should change the **User and event data retention** (for example, see the [entry for OTel.io][otel-ga]) from the default of 2 months to 14 months for all websites? (I've done it for OTel.) That config page has the following text:

> You can change the retention period for data you send that is associated with cookies, user identifiers, or advertising identifiers. These controls don’t affect most standard reporting, which is based on aggregated data. Changes to these settings take effect after 24 hours. [Learn more](https://support.google.com/analytics/answer/7667196?hl=en_US&utm_id=ad)

It isn't clear what gets deleted.

[otel-ga]: https://analytics.google.com/analytics/web/#/a163836834p321904186/admin/datapolicies/dataretention

**Comment by chalin** [comment]
Woohoo, Kubernetes.io is done - https://github.com/kubernetes/website/issues/35299!

**Comment by chalin** [comment]
All done! 😅 ✨
