### ISSUE TITLE
Suggested doc: best practices for site search

### ISSUE THREAD

**Issue by nate-double-u** [cncf/techdocs#115]
There are several tools available for projects to use to let their readers search onsite documentation.
* what are the options
* what are the pros/cons of each
* when is it best to use one over another

**Comment by nate-double-u** [comment]
@thisisobate I think your work on https://github.com/vitessio/website/pull/1119 would make a great start for this. Would you like to put together an outline as a start?

**Comment by thisisobate** [comment]
Sure thingy!
