### ISSUE TITLE
Recover CNCF Google Tag Manager (GTM) account

### ISSUE THREAD

**Issue by chalin** [cncf/techdocs#127]
CNCF has a GTM account, which we need to recover. Proof of the account:

- https://github.com/fluent/fluentd-website/pull/100

The CNCF GTM ID used in that PR is `GTM-TFCP8WJ`.

/assign @nate-double-u - as requested by @amye in this [Slack thread](https://cloud-native.slack.com/archives/G01CSL044G0/p1658873941606089?thread_ts=1658845114.977809&cid=G01CSL044G0)
/cc @caniszczyk

**Comment by chalin** [comment]
According to [[GA4] How Google Analytics is organized][org], under **Organization**:

> ... an organization could have the following configuration:
>
> - Organization
>   - Analytics account
>     - Analytics property
>   - Google Tag Manager account

So who ever has an organization-level access, should have access to the CNCF GTM account too :).

Any progress on this @nate-double-u? What's holding us back? Can we break the problem(s) down into smaller steps to make some headway?

[org]: https://support.google.com/analytics/answer/9303323

**Comment by nate-double-u** [comment]
I have access to the account we're to use to setup the org with now. I briefly took a look at actually creating it earlier this week and will revisit before i head out on vacation (today or tomorrow)

**Comment by chalin** [comment]
> we want to use the existing CNCF Organization -- the one that created the **CNCF projects** account -- to access the existing CNCF GTM account(s).

@nate-double-u - any progress on this? I'm starting work on another CNCF project that is using GTM.

**Comment by nate-double-u** [comment]
@chalin, does the projects@cncf.io account solve this issue?

**Comment by chalin** [comment]
Closing as no longer relevant -- #108 is done, and so we've moved on to GA4.
