### ISSUE TITLE
Create a place for language-specific localization guides

### ISSUE THREAD

**Issue by rolfedh** [cncf/techdocs#129]
User story: As a project manager and contributor to one of the projects under the CNCF umbrella, I want a set of CNCF localization guides the localization teams on my project can use. Or, I want a set of guides whose licensing permits me to freely I can copy and adapt them to meet my project's needs. 

Currently, it seems like a set of guides that fully meets these requirements might not be available. Various guides are available on the Internet, but lack the licensing information for CNCF projects to copy and re-use them.

**Comment by nate-double-u** [comment]
> /assign rolfedh

we don’t have the bot’s on this repo 😅
