### ISSUE TITLE
CNCFSD-1094 DNS management for Metal3.io

### ISSUE THREAD

**Issue by nate-double-u** [cncf/techdocs#138]
https://cncfservicedesk.atlassian.net/browse/CNCFSD-1094

**Comment by nate-double-u** [comment]
Closed as a duplicate of https://cncfservicedesk.atlassian.net/browse/CNCFSD-1505

**Comment by chalin** [comment]
@nate-double-u - let me know how that goes. Thx

**Comment by chalin** [comment]
Oh, sorry, I hadn't seen that you'd created #161. I've subscribed to #161 to follow progress. Thx
