### ISSUE TITLE
remove .vscode/cspell.json

### ISSUE THREAD

**Issue by nate-double-u** [cncf/techdocs#146]
Do we need the [.vscode/cspell.json](https://github.com/cncf/techdocs/blob/main/.vscode/cspell.json) file? or the `.vscode` directory?

Generally I like to keep IDE files out of repos unless there's a pretty good reason to include them.

_Originally posted by @nate-double-u in https://github.com/cncf/techdocs/pull/123#pullrequestreview-1148300251_

**Comment by chalin** [comment]
I'd vote to keep it :). For details, see https://github.com/cncf/techdocs/pull/123#issuecomment-1299247416.

**Comment by Nandini99-git** [comment]
The answer to your  question could be that it's up to your choice.

**Comment by nate-double-u** [comment]
> I'd vote to keep it :). For details, see https://github.com/cncf/techdocs/pull/123#issuecomment-1299247416.

Thanks for reminding me of the context 😅
