### ISSUE TITLE
Restore labels

### ISSUE THREAD

**Issue by nate-double-u** [cncf/techdocs#154]
Labels in this repo are managed with the [.github/settings.yml](https://github.com/cncf/techdocs/tree/main/.github/settings.yml) file.

If a label is added via the github UI, it will be removed when the .github/settings.yml file is updated.

We should find and re-add labels we have lost due to this:
- [ ] admin https://github.com/cncf/techdocs/pull/155

(please update as labels are identified)

**Comment by chalin** [comment]
I think that this can be closed.

**Comment by nate-double-u** [comment]
> I think that this can be closed.

agreed
