### ISSUE TITLE
CNCFSD-1468 Request for support on Dapr Docs

### ISSUE THREAD

**Issue by nate-double-u** [cncf/techdocs#158]
https://cncfservicedesk.atlassian.net/browse/CNCFSD-1468

**Request for Support on Dapr Docs:** Nicholas G. requested a meeting to discuss how CNCF can assist the [Dapr project](https://dapr.io/) with its documentation efforts.

@thisisobate is heading up this work.

**Comment by thisisobate** [comment]
The [PR](https://github.com/dapr/website/pull/80) for this work is merged.
Awaiting the maintainers to publish the new website to live.

**Comment by nate-double-u** [comment]
Deploy preview: https://deploy-preview-80--daprio.netlify.app/

**Comment by nate-double-u** [comment]
Closing as complete, Uche's work has been merged into a new-website branch that is awaiting design assets.
