### ISSUE TITLE
Archive SMI website

### ISSUE THREAD

**Issue by nate-double-u** [cncf/techdocs#194]
Archive SMI website as the project has been archived.

Context:
- https://cloud-native.slack.com/archives/CUJ6W5TLM/p1695687133669949
- https://github.com/cncf/toc/pull/1156#issuecomment-1734389031
- https://github.com/servicemeshinterface/smi-spec.io/issues/69
- https://github.com/cncf/toc/blob/main/proposals/archive/smi.md
- https://github.com/cncf/toc/issues/1180

**Comment by chalin** [comment]
@amye - has there been a blog post announcing the archiving yet, like [CNCF Archives the OpenTracing Project](https://www.cncf.io/blog/2022/01/31/cncf-archives-the-opentracing-project/)? Is one planned? /cc @caniszczyk 

Also, what is the link to the archival issue?

**Comment by chalin** [comment]
@amye - I think I found it:

- https://github.com/cncf/toc/issues/1180

**Comment by chalin** [comment]
And found the blog post!

- https://www.cncf.io/blog/2023/10/03/cncf-archives-the-service-mesh-interface-smi-project/

**Comment by chalin** [comment]
Per

- https://github.com/servicemeshinterface/smi-spec.io/issues/69

I'd say we're done here. Closing -- feel free to reopen if you think there is more to do @nate-double-u.

**Comment by nate-double-u** [comment]
Thanks @chalin!
