### ISSUE TITLE
Ensure 100% of CNCF projects have a site - 2024Q2

### ISSUE THREAD

**Issue by nate-double-u** [cncf/techdocs#196]
To start, let's find out how many sites _actually_ have no website. 

For a first pass let's look at [CLOMonitor: CNCF projects with no site listed](https://clomonitor.io/search?not_passing_check=website&foundation=cncf&page=1) to generate a list of projects to check. Some CLOMonitor entries report no website even if there is a site -- this is an artifact of how CLOMonitor checks. When we find projects that are mis-reported, we should open an issue with the project to make the update to correct the CLOMonitor report.

Once we get a better list of sites that _really_ don't have a website, we can build a list of projects to reach out to.

Follows up on:
* https://github.com/cncf/workflow/issues/467
* https://github.com/cncf/workflow/issues/856

| Project (CLOMonitor link) | Has website | CLOMonitor says it has a website | github org/repo | repo lists URL | upstream issue/comment | Note |
|---|:---:|:---:|---|:---:|---|---|
| [Carvel](https://clomonitor.io/projects/cncf/carvel) | [carvel.dev](https://carvel.dev/) |  ✅ |  [carvel-dev/carvel](https://github.com/carvel-dev/carvel) | ✅ | [https://github.com/cncf/clomonitor/pull/1392](https://github.com/cncf/clomonitor/pull/1392) | Fixed
| [Confidential Containers](https://clomonitor.io/projects/cncf/confidential-containers) | ❌ | ❌ | [confidential-containers](https://github.com/confidential-containers) | ❌ |
| [Contour](https://clomonitor.io/projects/cncf/contour) | [projectcontour.io](https://projectcontour.io/) |  ✅ | [projectcontour/community](https://github.com/projectcontour/community) |  ✅ |[https://github.com/projectcontour/community/issues/41](https://github.com/projectcontour/community/issues/41) | Fixed
| [Emissary-Ingress](https://clomonitor.io/projects/cncf/emissary-ingress) |[https://www.getambassador.io/docs/emissary](https://www.getambassador.io/docs/emissary) |  ✅ | [emissary-ingress/community](https://github.com/emissary-ingress/community) |  ✅ | [https://github.com/emissary-ingress/community/issues/10](https://github.com/emissary-ingress/community/issues/10) | Fixed
| [Konveyor](https://clomonitor.io/projects/cncf/konveyor) | [konveyor.io](https://www.konveyor.io/) |  ✅ | [konveyor/community](https://github.com/konveyor/community) |  ✅ | [https://github.com/konveyor/community/issues/72](https://github.com/konveyor/community/issues/72) | Fixed
| [Krator](https://clomonitor.io/projects/cncf/krator) | [docs.rs/crate/krator](https://docs.rs/crate/krator/latest) | ❌ |[krator-rs/krator](https://github.com/krator-rs/krator)| ❌ | [https://github.com/krator-rs/krator/issues/75](https://github.com/krator-rs/krator/issues/75) | This project does not have an actual website.
| [KubeClipper](https://clomonitor.io/projects/cncf/kubeclipper) | [kubeclipper.io](https://kubeclipper.io/) | ❌ | [kubeclipper/community](https://github.com/kubeclipper/community) | ❌ | [https://github.com/kubeclipper/community/issues/9](https://github.com/kubeclipper/community/issues/9)
| [KubeEdge](https://clomonitor.io/projects/cncf/kube-edge) | [kubeedge.io](https://kubeedge.io/) |  ✅ | [kubeedge/community](https://github.com/kubeedge/community) |  ✅ | [https://github.com/kubeedge/community/issues/191](https://github.com/kubeedge/community/issues/191) | Fixed
| [Kubeflow](https://clomonitor.io/projects/cncf/kubeflow) | [kubeflow.org](https://www.kubeflow.org/) | ❌ | [kubeflow/community](https://github.com/kubeflow/community)| ❌ | [https://github.com/kubeflow/community/issues/681](https://github.com/kubeflow/community/issues/681)
| [Kuberhealthy](https://clomonitor.io/projects/cncf/kuberhealthy) | ❌ | ❌ | [kuberhealthy/kuberhealthy](https://github.com/kuberhealthy/kuberhealthy) | ❌ | [https://github.com/kuberhealthy/kuberhealthy/issues/1176](https://github.com/kuberhealthy/kuberhealthy/issues/1176)
| [kube-vip](https://clomonitor.io/projects/cncf/kube-vip) | [kube-vip.io](https://kube-vip.io/) |  ✅ | [kube-vip/kube-vip](https://github.com/kube-vip/kube-vip) |  ✅ | [https://github.com/kube-vip/kube-vip/issues/701](https://github.com/kube-vip/kube-vip/issues/701) | Fixed
| [KubeVirt](https://clomonitor.io/projects/cncf/kubevirt) | [kubevirt.io](https://kubevirt.io/) | ❌ | [kubevirt/community](https://github.com/kubevirt/community)| ❌ | [https://github.com/kubevirt/community/issues/253](https://github.com/kubevirt/community/issues/253)
| [Notary](https://clomonitor.io/projects/cncf/notary) | [notaryproject.dev](https://notaryproject.dev/) |  ✅ | [notaryproject/notary](https://github.com/notaryproject/notary)|  ✅ | https://github.com/notaryproject/notary/issues/1697 | Fixed
| [OpenGitOps](https://clomonitor.io/projects/cncf/open-gitops) | [opengitops.dev](https://opengitops.dev/) | ❌ | [open-gitops/project](https://github.com/open-gitops/project)| ❌ | [https://github.com/open-gitops/project/issues/171](https://github.com/open-gitops/project/issues/171)
| [Opreator Framework](https://clomonitor.io/projects/cncf/operator-framework) | [operatorframework.io](https://operatorframework.io/) | ❌ | [operator-framework/community](https://github.com/operator-framework/community) | ❌ | [https://github.com/operator-framework/community/issues/101](https://github.com/operator-framework/community/issues/101)
| [ORAS](https://clomonitor.io/projects/cncf/oras) | [oras.land](https://oras.land/) |  ✅ | [oras-project/community](https://github.com/oras-project/community)|  ✅ | [https://github.com/oras-project/community/issues/57](https://github.com/oras-project/community/issues/57) | Fixed
| [PARSEC](https://clomonitor.io/projects/cncf/parsec) | [parsec.community](https://parsec.community/) |  ✅ | [parallaxsecond/community](https://github.com/parallaxsecond/community)|  ✅ | [https://github.com/parallaxsecond/community/issues/124](https://github.com/parallaxsecond/community/issues/124) | Fixed
| [Piraeus](https://clomonitor.io/projects/cncf/piraeus) | [piraeus.io](https://piraeus.io/) |  ✅ | [piraeusdatastore/piraeus](https://github.com/piraeusdatastore/piraeus)|  ✅ | [https://github.com/piraeusdatastore/piraeus/issues/166](https://github.com/piraeusdatastore/piraeus/issues/166) | Fixed
| [sealer](https://clomonitor.io/projects/cncf/sealer) | [sealer.cool](http://sealer.cool/) | ❌ | [sealerio/community](https://github.com/sealerio/community)| ❌ | [https://github.com/sealerio/community/issues/9](https://github.com/sealerio/community/issues/9)
| [SOPS](https://clomonitor.io/projects/cncf/sops) | [getsops.io](https://getsops.io) |  ✅ | [getsops/sops](https://github.com/getsops/sops)|  ✅ | [https://github.com/getsops/sops/issues/1395](https://github.com/getsops/sops/issues/1395) | Fixed
| [Submariner](https://clomonitor.io/projects/cncf/submariner) | [submariner.io](https://submariner.io/) |  ✅ | [submariner-io/submariner](https://github.com/submariner-io/submariner)|  ✅ | [https://github.com/submariner-io/submariner/issues/2858](https://github.com/submariner-io/submariner/issues/2858) | Fixed
| [Volcano](https://clomonitor.io/projects/cncf/volcano) | [volcano.sh](https://volcano.sh/en/) | ❌ | [volcano-sh/community](https://github.com/volcano-sh/community)| ❌ | [https://github.com/volcano-sh/community/issues/47](https://github.com/volcano-sh/community/issues/47)

\* [CLOMonitor Website check info](https://clomonitor.io/docs/topics/checks/#website)

**Comment by nate-double-u** [comment]
@tegioz, There are a couple sites on this list that should probably pass the CLOMonitor test -- carvel & projectcontour -- are they listing their sites in the wrong spot in their github org?

**Comment by tegioz** [comment]
Hi @nate-double-u 👋

The `website` check is part of the [community check set](https://clomonitor.io/docs/topics/checks/), so it's run on the repository that has that check set assigned. This check verifies that a website url is listed on that repository, as described in the docs:

<img width="1269" alt="ah" src="https://github.com/cncf/techdocs/assets/1213902/0690d1a3-a46b-4952-895e-ecaa2358ab0c">

### Contour

In you go to the Contour's CLOMonitor page, you'll see that the repository with the `community` check set is <https://github.com/projectcontour/community>.  But that repository doesn't have a website configured yet.

<img width="1269" alt="contour" src="https://github.com/cncf/techdocs/assets/1213902/02e73f58-0652-4176-9f61-7534f61ad5d3">

### Carvel

This one is more interesting 😉 In the Carvel's CLOMonitor page, the repository with the `community` check set is <https://github.com/vmware-tanzu/carvel>. If you visit that url in your browser, you'll notice that you'll be redirected to <https://github.com/carvel-dev/carvel>. However, and this could a GitHub problem, when we try to collect information from `vmware-tanzu/carvel` using the GitHub API from CLOMonitor, we get redirected to `carvel-dev/carvel-community` instead of to the correct one. My guess is that they renamed the repository twice, and somehow this got the redirection on the API side confused, but not sure. Anyway, the community repository listed in CLOMonitor isn't correct anyway, so the solution would be to update it in the [data file](https://github.com/cncf/clomonitor/blob/b5ac6791f910bf7c5ad9d506145a2a8871f334ae/data/cncf.yaml#L2742). As soon as that's done and CLOMonitor checks that repository again the website check should pass.

Hope this helps!

**Comment by nate-double-u** [comment]
Closing as stale and outdated. We've now got a Google Sheet to help track this.
