### ISSUE TITLE
Ensure all projects have correct trademark disclaimer - 2023Q4

### ISSUE THREAD

**Issue by nate-double-u** [cncf/techdocs#198]
As a follow up to [#196](https://github.com/cncf/techdocs/issues/196), we want to identify projects that don't have the official Linux Foundation trademark listed on their website.

Our approach is to discover these projects, then reach out to their respective communities to update their website accordingly.

| Project (CLOMonitor link) | Has website | website lists Trademark | upstream issue/comment | Note |
|---|:---:|:---:|---|---|
| [Akri](https://clomonitor.io/projects/cncf/akri) | [docs.akri.sh](https://docs.akri.sh/) | ❌ | https://github.com/project-akri/akri-docs/issues/107 |
| [Armada](https://clomonitor.io/projects/cncf/armada) | [armadaproject.io](https://armadaproject.io/) | ❌ | https://github.com/armadaproject/armada/issues/3245 |
| [Artifact-hub](https://clomonitor.io/projects/cncf/artifact-hub) | [artifacthub.io](https://artifacthub.io/) | ❌ | https://github.com/artifacthub/hub/issues/3620 |
| [Backstage](https://clomonitor.io/projects/cncf/backstage) | [backstage.io](https://backstage.io/) | ❌ | https://github.com/backstage/backstage/issues/22477 |
| [Beyond Frontend](https://clomonitor.io/projects/cncf/bfe) | [bfe-networks.net](https://www.bfe-networks.net/) | ❌ | https://github.com/bfenetworks/bfe/issues/1147 |
| [Carina](https://clomonitor.io/projects/cncf/carina) | [carina-io.github.io](https://carina-io.github.io/) | ❌ | https://github.com/carina-io/carina-io.github.io/issues/1 |
| [Cloud-custodian](https://clomonitor.io/projects/cncf/cloud-custodian) | [cloudcustodian.io](https://cloudcustodian.io/) | ❌ | https://github.com/cloud-custodian/cloud-custodian/issues/9258 |
| [Cloud-provider-aws](https://clomonitor.io/projects/cncf/cloud-provider-aws) | [cloud-provider-aws.sigs.k8s.io](https://cloud-provider-aws.sigs.k8s.io/) | ❌ | https://github.com/kubernetes/cloud-provider-aws/issues/837 |
| [Clusterpedia](https://clomonitor.io/projects/cncf/clusterpedia) | [clusterpedia.io](https://clusterpedia.io/) | ❌ | https://github.com/clusterpedia-io/website/issues/84 |
| [CNI-genie](https://clomonitor.io/projects/cncf/cni-genie) | [cnigenie.netlify.app](https://cnigenie.netlify.app/en/) | ❌ | https://github.com/cni-genie/website/issues/4 |
| [Confidential containers](https://clomonitor.io/projects/cncf/confidential-containers) | [cloud-provider-aws.sigs.k8s.io](https://cloud-provider-aws.sigs.k8s.io/) | ❌ | https://github.com/confidential-containers/confidentialcontainers.org/issues/26 |
| [Containerssh](https://clomonitor.io/projects/cncf/containerssh) | [containerssh.io](https://containerssh.io/) | ❌ | https://github.com/ContainerSSH/containerssh.github.io/issues/53 |
| [Curiefense](https://clomonitor.io/projects/cncf/curiefense) | [curiefense.io](https://www.curiefense.io/) | ❌ | https://github.com/curiefense/curiefense/issues/1260 |
| [Curve](https://clomonitor.io/projects/cncf/curve) | [opencurve.io](https://opencurve.io/) | ❌ | https://github.com/opencurve/curve-dashboard/issues/14 |
| [Devfile](https://clomonitor.io/projects/cncf/devfile) | [devfile.io](https://devfile.io/) | ❌ |  | check flagged as exempt |
| [Devspace](https://clomonitor.io/projects/cncf/devspace) | [devspace.sh](https://www.devspace.sh/) | ❌ | https://github.com/devspace-sh/devspace/issues/2795 |
| [Distribution](https://clomonitor.io/projects/cncf/distribution) | [distribution.github.io/distribution](https://distribution.github.io/distribution/) | ❌ | https://github.com/distribution/distribution/issues/4264 |
| [Emissary-ingress](https://clomonitor.io/projects/cncf/emissary-ingress) | [getambassador.io/docs/emissary](https://www.getambassador.io/docs/emissary) | ❌ | https://github.com/emissary-ingress/community/issues/11 |
| [Eraser](https://clomonitor.io/projects/cncf/eraser) | [eraser-dev.github.io/eraser/](https://eraser-dev.github.io/eraser/docs/) | ❌ | https://github.com/eraser-dev/eraser/issues/963 |
| [External DNS](https://clomonitor.io/projects/cncf/external-dns) | ❌ | ❌ | https://github.com/kubernetes-sigs/external-dns/issues/4203 | Looks like project has a website (see https://github.com/kubernetes-sigs/external-dns/blob/master/mkdocs.yml) but can't find the link | 
| [FabEdge](https://clomonitor.io/projects/cncf/fabedge) | [fabedge.io](http://www.fabedge.io/) | ❌ | https://github.com/FabEdge/fabedge/issues/441 |
| [Flagger](https://clomonitor.io/projects/cncf/flagger) | [docs.flagger.app](https://docs.flagger.app/) | ❌ | https://github.com/fluxcd/flagger/issues/1586 |
| [Fluentd](https://clomonitor.io/projects/cncf/fluentd) | [fluentd.org](https://www.fluentd.org/) | ❌ | https://github.com/fluent/fluentd-website/issues/296 |
| [Kubernetes gateway api](https://clomonitor.io/projects/cncf/gateway-api) | [gateway-api.sigs.k8s.io](https://gateway-api.sigs.k8s.io/) | ❌ | https://github.com/kubernetes-sigs/gateway-api/issues/2735 |
| [Hexa policy orchestrator](https://clomonitor.io/projects/cncf/hexapolicyorchestrator) | [hexaorchestration.org](https://hexaorchestration.org/) | ❌ | https://github.com/hexa-org/policy-orchestrator/issues/388 |
| [Hwameistor](https://clomonitor.io/projects/cncf/hwameistor) | [hwameistor.io](https://hwameistor.io/) | ❌ | https://github.com/hwameistor/hwameistor/issues/1372 |
| [Inclavare containers](https://clomonitor.io/projects/cncf/inclavare) | [inclavare-containers.io](https://inclavare-containers.io/) | ❌ | https://github.com/inclavare-containers/inclavare-containers.io/issues/3 |
| [K8up](https://clomonitor.io/projects/cncf/k8up) | [k8up.io](https://k8up.io/) | ✅ |  | CLOmonitor is flaky |
| [Karpenter](https://clomonitor.io/projects/cncf/karpenter) | ❌ | ❌ |  | project has no website | 
| [Keptn](https://clomonitor.io/projects/cncf/keptn) | [keptn.sh](https://keptn.sh/) | ❌ | https://github.com/keptn/lifecycle-toolkit/issues/2874 |
| [Keylime](https://clomonitor.io/projects/cncf/keylime) | [keylime.dev](https://keylime.dev/) | ❌ | https://github.com/keylime/keylime/issues/1518 |
| [Knative](https://clomonitor.io/projects/cncf/knative) | [knative](https://knative/) | ❌ | https://github.com/knative/docs/issues/5829 |
| [Kompose](https://clomonitor.io/projects/cncf/kompose) | [kompose.io](https://kompose.io/) | ❌ | https://github.com/kubernetes/kompose/issues/1815 |
| [Kpt](https://clomonitor.io/projects/cncf/kpt) | [kpt.dev](https://kpt.dev/) | ❌ | https://github.com/kptdev/kpt/issues/4112 |
| [Krator](https://clomonitor.io/projects/cncf/krator) | ❌ | ❌ |  | project has no website |
| [Krustlet](https://clomonitor.io/projects/cncf/krustlet) | [krustlet.dev](https://krustlet.dev/) | ❌ | https://github.com/krustlet/krustlet.dev/issues/15 |
| [kubearmor](https://clomonitor.io/projects/cncf/kubearmor) | [kubearmor.io](https://kubearmor.io/) | ❌ | https://github.com/kubearmor/kubearmor.io/issues/41 |
| [Kubeclipper](https://clomonitor.io/projects/cncf/kubeclipper) | [kubeclipper.io](https://kubeclipper.io/) | ❌ | https://github.com/kubeclipper/kubeclipper.github.io/issues/57 |
| [Kubeflow](https://clomonitor.io/projects/cncf/kubeflow) | [kubeflow.org](https://www.kubeflow.org/) | ❌ | https://github.com/kubeflow/website/issues/3664 |
| [Kube-ovn](https://clomonitor.io/projects/cncf/kube-ovn) | [kubeovn.github.io](https://kubeovn.github.io/docs/en/) | ❌ | https://github.com/kubeovn/docs/issues/153 |
| [Kuberhealthy](https://clomonitor.io/projects/cncf/kuberhealthy) | ❌ | ❌ |  | project has no website |
| [Kube-rs](https://clomonitor.io/projects/cncf/kube-rs) | [kube.rs](https://kube.rs/) | ❌ | https://github.com/kube-rs/website/issues/56 |
| [Kube state metrics](https://clomonitor.io/projects/cncf/kube-state-metrics) | ❌ | ❌ |  | project has no website |
| [Kubevela](https://clomonitor.io/projects/cncf/kubevela) | [oam.dev](https://oam.dev/) | ❌ | https://github.com/oam-dev/oam-dev.github.io/issues/47 |
| [Kube-vip](https://clomonitor.io/projects/cncf/kube-vip) | [kube-vip.io](https://kube-vip.io/) | ❌ | https://github.com/kube-vip/website/issues/38 |
| [Kubevirt](https://clomonitor.io/projects/cncf/kubevirt) | [kubevirt.io](https://kubevirt.io/) | ✅ | https://github.com/kubevirt/community/issues/253 | Community page does not link to the website |
| [Kudo](https://clomonitor.io/projects/cncf/kudo) | [kudo.dev](https://kudo.dev/) | ❌ | https://github.com/kudobuilder/kuttl.dev/issues/70 |
| [kueue](https://clomonitor.io/projects/cncf/kueue) | [kueue.sigs.k8s.io](https://kueue.sigs.k8s.io/) | ❌ | https://github.com/kubernetes-sigs/kueue/issues/1647 |
| [Linkerd](https://clomonitor.io/projects/cncf/linkerd) | [linkerd.io](https://linkerd.io/) | ❌ | https://github.com/linkerd/website/issues/1729 |
| [Merbridge](https://clomonitor.io/projects/cncf/merbridge) | [merbridge.io](https://merbridge.io/) | ❌ | https://github.com/merbridge/website/issues/45 |
| [Meshery](https://clomonitor.io/projects/cncf/meshery) | [meshery.io](https://meshery.io/) | ❌ | https://github.com/meshery/meshery.io/issues/1622 |
| [Minikube](https://clomonitor.io/projects/cncf/minikube) | [minikube.sigs.k8s.io](https://minikube.sigs.k8s.io/) | ❌ | https://github.com/kubernetes/minikube/issues/18055 |
| [Network service mesh](https://clomonitor.io/projects/cncf/network-service-mesh) | [networkservicemesh.io](https://www.networkservicemesh.io/) | ❌ | https://github.com/networkservicemesh/site/issues/277 |
| [Nocalhost](https://clomonitor.io/projects/cncf/nocalhost) | [nocalhost.dev](https://nocalhost.dev/) | ❌ | https://github.com/nocalhost/nocalhost.github.io/issues/228 |
| [Open policy agent](https://clomonitor.io/projects/cncf/opa) | [openpolicyagent.org](https://openpolicyagent.org/) | ❌ |  https://github.com/open-policy-agent/opa/issues/6557 |
| [Open ebs](https://clomonitor.io/projects/cncf/openebs) | [openebs.io](https://openebs.io/) | ❌ | https://github.com/openebs/website/issues/390 |
| [Open elb](https://clomonitor.io/projects/cncf/openelb) | [openelb.io](https://openelb.io/) | ❌ | https://github.com/openelb/website/issues/89 |
| [Open feature](https://clomonitor.io/projects/cncf/openfeature) | [openfeature.dev](https://openfeature.dev/) | ❌ | https://github.com/open-feature/openfeature.dev/issues/391 |
| [Open gitops](https://clomonitor.io/projects/cncf/open-gitops) | [opengitops.dev](https://opengitops.dev/) | ❌ | https://github.com/open-gitops/project/issues/171 |
| [Open metrics](https://clomonitor.io/projects/cncf/open-metrics) | [openmetrics.io](https://openmetrics.io/) | ❌ | https://github.com/OpenObservability/OpenMetrics/issues/266 |
| [Operator framework](https://clomonitor.io/projects/cncf/operator-framework) | [operatorframework.io]( https://operatorframework.io/) | ❌ | https://github.com/operator-framework/operator-framework.io/issues/40 |
| [Oras](https://clomonitor.io/projects/cncf/oras) | [oras.land](https://oras.land/) | ❌ | https://github.com/oras-project/oras-www/issues/279 |
| [Sealer](https://clomonitor.io/projects/cncf/sealer) | [sealer.cool](https://sealer.cool/) | ❌ | https://github.com/sealerio/community/issues/9 |
| [Serverless workflow](https://clomonitor.io/projects/cncf/serverless-workflow) | [serverlessworkflow.io](http://serverlessworkflow.io/) | ❌ | https://github.com/serverlessworkflow/serverlessworkflow.github.io/issues/196 |
| [Skooner](https://clomonitor.io/projects/cncf/skooner) | [skooner.io](https://skooner.io/) | ❌ | https://github.com/skooner-k8s/skooner-website/issues/1 |
| [Slimtoolkit](https://clomonitor.io/projects/cncf/slimtoolkit) | [slimtoolkit.org](https://slimtoolkit.org/) | ❌ | https://github.com/slimtoolkit/slimtoolkit.github.io/issues/2 |
| [Service mesh perfromance](https://clomonitor.io/projects/cncf/smp) | [smp-spec.io](https://smp-spec.io/) | ❌ | https://github.com/service-mesh-performance/service-mesh-performance/issues/414 |
| [Sops](https://clomonitor.io/projects/cncf/sops) | [getsops.io](https://getsops.io/) | ❌ |  | getsops.io links back to the sops github org page instead of a valid website |
| [Telepresence](https://clomonitor.io/projects/cncf/telepresence) | [telepresence.io](https://telepresence.io/) | ❌ | https://github.com/telepresenceio/telepresence.io/issues/202 |
| [Teller](https://clomonitor.io/projects/cncf/teller) | [tlr.dev](https://tlr.dev/) | ❌ | https://github.com/tellerops/teller/issues/230 |
| [Thanos](https://clomonitor.io/projects/cncf/thanos) | [thanos.io](https://thanos.io/) | ❌ | https://github.com/thanos-io/thanos/issues/7104 |
| [Tikv](https://clomonitor.io/projects/cncf/tikv) | [tikv.org](https://tikv.org/) | ❌ | https://github.com/tikv/website/issues/351 |
| [Virtual kubelet](https://clomonitor.io/projects/cncf/virtual-kubelet) | [virtual-kubelet.io](https://virtual-kubelet.io/) | ❌ | https://github.com/virtual-kubelet/virtual-kubelet/issues/1200 |
| [Volcano](https://clomonitor.io/projects/cncf/volcano) | [volcano.sh](https://volcano.sh/) | ❌ | https://github.com/volcano-sh/community/issues/47 |
| [Visual studio code kubernetes-tools](https://clomonitor.io/projects/cncf/vscode-kubernetes-tools) | [vscode-kubernetes-tools.github.io](https://vscode-kubernetes-tools.github.io/vscode-kubernetes-tools/itor.io/projects/cncf/kudo) | ❌ | https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1250 |
| [Xline](https://clomonitor.io/projects/cncf/xline) | [xline.cloud](https://xline.cloud/) | ❌ | https://github.com/datenlord/xline-home/issues/4 |
| [Zot](https://clomonitor.io/projects/cncf/zot) | [zotregistry.io](https://zotregistry.io/) | ❌ | https://github.com/project-zot/project-zot.github.io/issues/152 |

\* [CLOMonitor Trademarks check info](https://clomonitor.io/docs/topics/checks/#trademark-disclaimer)
\* [CLOMonitor: CNCF projects with no trademarks listed](https://clomonitor.io/search?foundation=cncf&not_passing_check=trademark_disclaimer&page=1)

**Comment by nate-double-u** [comment]
Let's start with sites that we have worked on this year.

**Comment by kapilt** [comment]
is this a home page request or apply to every page on the domain consideration? we have different web site generators apply at different parts of the urlspace, so would appreciate clarification.

**Comment by thisisobate** [comment]
Already answered in the issue @kapilt

**Comment by nate-double-u** [comment]
> is this a home page request or apply to every page on the domain consideration? we have different web site generators apply at different parts of the urlspace, so would appreciate clarification.

It's best to put any trademark/copyright messages in a footer that can be displayed across all the pages of a site. That said, if this is a problem, we can take a look on a case by case basis to see what's best.

**Comment by nate-double-u** [comment]
Closing as stale and outdated. We've now got a Google Sheet to help track this.
