### ISSUE TITLE
Encourage more projects to use Artifact Hub

### ISSUE THREAD

**Issue by nate-double-u** [cncf/techdocs#213]
See if we can get more projects using https://artifacthub.io/ and embedding it on their websites like https://keptn.sh/docs/integrations/

**Comment by nate-double-u** [comment]
Looks like Keptn's new site hasn't kept the integrations, but we can still look into how best to leverage artifacthub with other sites.

**Comment by thisisobate** [comment]
This list tracks cncf projects with more than 1 package hosted on ArtifactHub.

| Org (ArtifactHub link) | upstream issue/comment | Note |
|---|---|---|
| [Argo](https://artifacthub.io/packages/search?repo=argo&sort=relevance&page=1) | https://github.com/argoproj/argo-site/issues/143 |  |
| [Prometheus](https://artifacthub.io/packages/search?org=prometheus&sort=relevance&page=1) | https://github.com/prometheus/docs/issues/2460 |  |
| [Kyverno](https://artifacthub.io/packages/search?org=kyverno&sort=relevance&page=1) |  |  |
| [Istio](https://artifacthub.io/packages/search?org=istio&sort=relevance&page=1) |  |  |
| [Cilium](https://artifacthub.io/packages/search?org=cilium&sort=relevance&page=1) |  |  |
| [cert-manager](https://artifacthub.io/packages/search?org=cert-manager&sort=relevance&page=1) |  |  |
| [kubewarden](https://artifacthub.io/packages/search?org=kubewarden&sort=relevance&page=1) |  |  |
| [Meshery](https://artifacthub.io/packages/search?org=meshery&sort=relevance&page=1) |  |  |
| [Rook](https://artifacthub.io/packages/search?org=rook&sort=relevance&page=1) |  |  |
| [Inspektor gadget](https://artifacthub.io/packages/search?org=inspektor-gadget&sort=relevance&page=1) |  |  |
| [Keptn](https://artifacthub.io/packages/search?org=keptn&sort=relevance&page=1) |  |  |
| [Jaeger](https://artifacthub.io/packages/search?org=jaegertracing&sort=relevance&page=1) |  |  |

**Comment by nate-double-u** [comment]
Closing as complete. Several issues opened encouraging folks to use Artifact hub.
