### ISSUE TITLE
CNCFSD-2191 LitmusChaos

### ISSUE THREAD

**Issue by nate-double-u** [cncf/techdocs#218]
https://cncfservicedesk.atlassian.net/browse/CNCFSD-2191

LitmusChaos has requested a TechDocs analysis

**Comment by prithvi1307** [comment]
Hey @nate-double-u we have applied for Graduation for LitmusChaos. The process has kickstarted and is progressing well. The docs review is an important item awaited. As an urgent request can we try expediting this?

**Comment by nate-double-u** [comment]
Congrats @prithvi1307, that's great news!

I'll chat with the team and see what we can do. We still have quite a backlog.

(Relevant PR: https://github.com/cncf/toc/pull/1297)

**Comment by nate-double-u** [comment]
Hi @prithvi1307, I think that we can probably bump this up the priority list a little bit, but I still don't think this will happen right away. My understanding is that the the TOC has a significant backlog themselves. 

I think that the TOC has about a 9 month backlog, and one of these analysis usually takes about 6 weeks.

**Comment by prithvi1307** [comment]
Thanks @nate-double-u thanks for the update. Understand the backlog on the TOC front but want to understand the backlog on the docs review team? Can we still target getting this done by mid-August?

**Comment by prithvi1307** [comment]
Thanks @dwelsch-esi 
Do we want to schedule a call or have any async discussions on what is required from the community?

**Comment by dwelsch-esi** [comment]
@prithvi1307 Good question. What is specifically required from the community:

Before the doc analysis PR is merged: Review the analysis and provide feedback: What your concerns are about the docs, what questions you have about the analysis, and any ideas you have about prioritizing and implementing issues brought up in the analysis.

After the PR is merged: Recruit contributors and work on the issues that are generated from the analysis.

It's also helpful if contributors who are involved in documentation gain some knowledge about the documentation process and how it integrates with OSS development. That can be as quick as reading some of the CNCF process docs (see below) or as involved as taking the docs for developers courses offered by LF/CNCF. 

What we've done in the past is to have a call once I've mostly completed the analysis but before I've written the issues, to give the community a chance to provide some informed input. I'll probably open the PR for this next week, at which point we can set up the call. You can also comment on the PR; we've had some very productive discussions there as well.

In the meantime, please feel free to discuss comments or concerns you have about the doc or the CNCF process via Slack or email. I would ask that anyone wanting to discuss the doc analysis process please read about the process first at the [CNCF TechDocs](https://github.com/cncf/techdocs/tree/main/docs) repo, especially the assistance.md, analysis/criteria.md, and sandbox-doc-primer.md files. (Litmus is past the sandbox stage, but that document contains a lot of info and terminology that's helpful to understanding the doc analysis.)

/cc @nate-double-u

**Comment by dwelsch-esi** [comment]
@prithvi1307 @umamukkara I've written a draft of the analysis for Litmus Chaos. I'd like to get your feedback on the document, then possibly meet with you and other stakeholders before completing the implementation plan and assessments. Can I ask you to please:
1. Read this short document so that we have a common framework for discussing the analysis:
  https://github.com/cncf/techdocs/blob/main/docs/sandbox-doc-primer.md
2. Then, review the analysis PR here:
  https://github.com/cncf/techdocs/pull/275

If you have any questions please don't hesitate to contact me. Thanks!
Dave

/cc @nate-double-u
