### ISSUE TITLE
[CI] Run basic markdown-file checks when a PR is submitted

### ISSUE THREAD

**Issue by chalin** [cncf/techdocs#232]
- [x] Set up checks via NPM packages and scripts - #231
- [ ] Set up GH actions to trigger on PR submission - #235

**Comment by chalin** [comment]
@nate-double-u - I don't seem to have the permissions to fully implement the tasks in this PR. Could my access permissions be bumped, if only for the period necessary to implement CI?

**Comment by nate-double-u** [comment]
I think we can bump your permissions, it's an update to the [cncf/people repo](https://github.com/cncf/people).

**Comment by nate-double-u** [comment]
Once approved, https://github.com/cncf/people/pull/464, will provide you Admin access to cncf/techdocs, @chalin.

**Comment by chalin** [comment]
Thanks @nate-double-u!
