### ISSUE TITLE
Switch to CLA for this repo

### ISSUE THREAD

**Issue by chalin** [cncf/techdocs#244]
@nate-double-u - is it easy to setup EasyCLA?

**Comment by nate-double-u** [comment]
Sorry I missed this. Why would you like to shift?

**Comment by chalin** [comment]
Given that **most contributors to this repo do so repeatedly**, it we'll be **saving time and effort by using CLA**. Such contributors, like the techdocs team, have all signed the CLA (once!) and will be able to forget about signing _every single commit_ in _every single_ PR submitted to this repo via the web i/f or otherwise.

Said another way: DCO isn't a good match for this repo IMHO. E.g., GitHub web i/f patch commits don't always work -- I end up having to pull it in locally, signing, and pushing back. That's time wasted.

Same thing for local development, especially for PRs with multiple commits. I often forget to sign, and only realize after having submitted the PR; and then I have to fix the issue retroactively.

**Comment by nate-double-u** [comment]
Thanks for laying out the argument. I brought it to the CNCF leadership team and we prefer to stay with DCO. I think that all CNCF repos use DCO (tho, I'd have to double check).

**Comment by chalin** [comment]
Ok, got it.
