### ISSUE TITLE
TUF analysis: Add specification to the new IA

### ISSUE THREAD

**Issue by chalin** [cncf/techdocs#271]
The current IA contains pages for the specification, but the new IA does not. I might suggest adding it as a top-nav entry to a **Specifications** page, that would contain a list of the current specification -- as given by https://theupdateframework.github.io/specification/.

Reference: https://github.com/cncf/techdocs/blob/main/analyses/0012-TUF/implementation.md#proposed-information-architecture-for-the-tuf-website

(Later, we can explore how we can embed this page as a part of the website at build time.)

/cc @lukpueh

**Comment by Dindihub** [comment]
> The current IA contains pages for the specification, but the new IA does not. I might suggest adding it as a top-nav entry to a **Specifications** page, that would contain a list of the current specification -- as given by https://theupdateframework.github.io/specification/.
> 
> Reference: https://github.com/cncf/techdocs/blob/main/analyses/0012-TUF/implementation.md#proposed-information-architecture-for-the-tuf-website
> 
> (Later, we can explore how we can embed this page as a part of the website at build time.)
> 
> /cc @lukpueh

Sounds good!
