### ISSUE TITLE
OKR2-1: Complete 5 docs assessments

### ISSUE THREAD

**Issue by celestehorgan** [cncf/techdocs#32]
Complete and publish 5 docs assessments by the end of the year, and provide ongoing support for any issues raised during the assessments.

**Comment by celestehorgan** [comment]
Q3 Update: 4/5 complete!

**Comment by celestehorgan** [comment]
Q4 Update: 5/5 complete 🎉

**Comment by chalin** [comment]
Woohoo! Great job!
