### ISSUE TITLE
OKR2-2: Perform docs assessments for all new CNCF projects upon acceptance

### ISSUE THREAD

**Issue by celestehorgan** [cncf/techdocs#33]
Perform a docs assessment for all new projects upon acceptance to CNCF. 

Unlike assessments for more mature projects, we anticipate that many of these assessments will start and finish at "they don't have a website" or "they only have a README for documentation". The goal is to establish a baseline and start to populate the website backlog queue.

**Comment by nate-double-u** [comment]
closing old OKRs since we are starting a new process.
