### ISSUE TITLE
OKR3-1: Create slide deck for New Project Onboarding session & run sessions quarterly

### ISSUE THREAD

**Issue by celestehorgan** [cncf/techdocs#34]
**Problem:** Projects don't know what services are available to them (Project services & docs services) via the CNCF. 

**Proposed solution**: Work with @amye to run a quarterly New Project Onboarding session which covers the following:

- What docs services projects can access
- What website services projects can access 
- Docs assessments 
- What project services projects can access 
- How they're expected to work with CNCF staff (via the service desk)

**Comment by nate-double-u** [comment]
closing old OKRs since we are starting a new process.
