### ISSUE TITLE
OKR3-2: Increase attendance at techdocs office hours by 25%

### ISSUE THREAD

**Issue by celestehorgan** [cncf/techdocs#35]
**Problem:** Techdocs office hours are the main way we interface with projects and teach them about the various things CNCF can do for projects, docs and website-wise. Increasing attendance at office hours means we see an increase in projects accessing the services we provide and an increase in maintainer satisfaction.

**Proposed solution:** TBD?

**Comment by nate-double-u** [comment]
closing old OKRs since we are starting a new process.
