### ISSUE TITLE
OKR1-1: Assess all new site projects/tickets against MVP requirements

### ISSUE THREAD

**Issue by celestehorgan** [cncf/techdocs#37]
Depends on https://github.com/cncf/techdocs/issues/30 

**Problem:** Same as https://github.com/cncf/techdocs/issues/30 , but additionally: This OKR is about better backlog management, project scoping, and (human-hour) resourcing.

**Proposed solution:** 
1. Update Docs assessment to evaluate against website MVP guidelines as well 
2. Assess all new website projects and tickets against MVP guidelines for their maturity level.
3. Provide a (rough) estimate of length of engagement based on MVP requirements in the ticket and do your best to stick to it!

**Comment by nate-double-u** [comment]
closing old OKRs since we are starting a new process.
