### ISSUE TITLE
OKR5-1: Start and run docs community meetings in the open with open agenda

### ISSUE THREAD

**Issue by celestehorgan** [cncf/techdocs#39]
**Problem:** When new docs contributors look to join CNCF projects, they don't have a place to "land", access mentorship, or generally interface with the ecosystem in a useful manner.

**Proposed solution:** Run techdocs updates meetings as an open community meeting with open agendas.

**Comment by nate-double-u** [comment]
closing old OKRs since we are starting a new process.
