### ISSUE TITLE
OKR5-2: Run two docs mentorships via LFX

### ISSUE THREAD

**Issue by celestehorgan** [cncf/techdocs#40]

**Comment by nate-double-u** [comment]
### Fall Term: September 1st - Nov 30th
* mentorships available on LFX Mentorship: July 15th, 2021
* mentee applications open: July 15th - August 12th (4 weeks)
* application review/admission decisions/HR paperwork: August 12th - August 31st

> Note: 
> Dates may vary based on project guidelines.
> Part-time terms will continue for three to six months based on project guidelines.

https://docs.linuxfoundation.org/lfx/mentorship/mentorship-program-timelines

**Comment by nate-double-u** [comment]
Some relevant links:
* https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2021/03-Fall
* https://docs.linuxfoundation.org/lfx/mentorship/mentor-guide

Sample docs related project ideas:
* https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2021/02-Summer#tremor-web-redesign---make-tremors-web-presence-awesome
* https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2021/02-Summer#improve-the-kubeedge-website
* https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2021/01-Spring#reading-materials-update-and-supplement

**Comment by celestehorgan** [comment]
Closing - done! 🎉
