### ISSUE TITLE
OKR-1: Improve website request turnaround time

### ISSUE THREAD

**Issue by celestehorgan** [cncf/techdocs#42]
This OKR focuses on resolving website-related tickets via the CNCF Service Desk in a more efficient and timeboxed manner, as well as enabling the team to template-ize web work better by working on our Hugo theme.

Sub-issues: 
#37 - Assess all new site projects/tickets against MVP requirements
~#31 - Release v1.0 of the https://github.com/cncf/hugo-netlify-starter~

**Comment by nate-double-u** [comment]
Closing as stale.
