### ISSUE TITLE
OKR-3: Grow visibility of techdocs team & CNCF services

### ISSUE THREAD

**Issue by celestehorgan** [cncf/techdocs#44]
This OKR centers around one of the CNCF's key goals of keeping maintainer satisfaction high. Many projects aren't aware this team exists and that these services are available to them (or how to access them if they are available.) This OKR focuses on raising awareness of the team and services available to projects. 

#34 - New project onboarding sessions quarterly  
#35 - Increase attendance at techdocs office hours by 25%

**Comment by nate-double-u** [comment]
closing old OKRs since we are starting a new process.
