### ISSUE TITLE
OKR-5: Grow mentorship and outside docs contributors

### ISSUE THREAD

**Issue by celestehorgan** [cncf/techdocs#46]
This OKR focuses on the docs team being a better open source citizen, as well as supporting the ongoing sustainability of the CNCF project ecosystem by mentoring new contributors into the communities we work with.

#39 - Start and run docs community meetings in the open with an open agenda 
~#40 - Run two docs mentorships via LFX~ 
#41 - Write a series of blog posts on contributing as a tech writer

**Comment by nate-double-u** [comment]
closing old OKRs since we are starting a new process.
