### ISSUE TITLE
Docs assessment for Kubernetes API Gateway

### ISSUE THREAD

**Issue by celestehorgan** [cncf/techdocs#60]

**Comment by celestehorgan** [comment]
@youngnick FYI.

**Comment by youngnick** [comment]
I think the things we're mainly looking for are around overall impressions and information architecture:
- What can we do to improve the first-look experience?
- Does the way the navigation is laid out make sense?
- Are we explaining the API concepts clearly enough for a technical but unfamiliar person to get how things should work?

My personal feeling is that we have a lot of great information there, but I don't think we're making it available well enough.

The website itself is at https://gateway-api.sigs.k8s.io/ - it's intended to be the main reference.

Known issues:
- We currently have a GEP (Gateway Enhancement Proposal) process, lifted from KEPs, and the GEPS are available on the site, but there's no nav to lead you there. I'm planning on fixing this, but it's not done yet.
-

**Comment by youngnick** [comment]
Oh, the title should also be "Docs assessment for Kubernetes Gateway API" - the name of the project is just Gateway API normally.

**Comment by nate-double-u** [comment]
https://github.com/cncf/mentoring/pull/454

**Comment by nate-double-u** [comment]
completed with https://github.com/cncf/techdocs/pull/109
