### ISSUE TITLE
Notary Project website

### ISSUE THREAD

**Issue by nate-double-u** [cncf/techdocs#61]
Repo: https://github.com/notaryproject/notaryproject.dev
Project board: https://github.com/notaryproject/notaryproject.dev/projects/1

Related: https://github.com/cncf/techdocs/issues/26

**Comment by celestehorgan** [comment]
Nate, is this roadblocked? Do you need a "Blocked" column for this?

**Comment by nate-double-u** [comment]
I think we can probably close this issue as the website is up now. Currently it is in an MVP state, and the actual docs are still primarily outside the site (linked from the menu bar).

@SteveLasker, what do you think? Can we call the site setup and close this issue? I'd  be happy to have other issues opened for specific docs work when you feel the project is ready for it.

**Comment by SteveLasker** [comment]
LGTM to close.

**Comment by nate-double-u** [comment]
Thanks Steve!
