### ISSUE TITLE
Add versioning to hugo-netlify-starter

### ISSUE THREAD

**Issue by kapunahelewong** [cncf/techdocs#63]
Though this is part of #50 it is sizable/time consuming, so I'm adding an issue to track it. 

@nate-double-u has to get credit too as he is also guiding me through this.

**Comment by nate-double-u** [comment]
WIP PR: https://github.com/cncf/hugo-netlify-starter/pull/109

**Comment by nate-double-u** [comment]
Is this still a project we're pursuing, with some of the discussions we've had re: Docsy, I wonder if this should be paused or closed.

/cc @celestehorgan @chalin

**Comment by nate-double-u** [comment]
Closing as we're moving in a different direction from the starter as it is.
