### ISSUE TITLE
Consider adding a label for each project refered to in the cncf/techdocs issues listing

### ISSUE THREAD

**Issue by nate-double-u** [cncf/techdocs#65]
It may be helpful to be able to sort on project as we start adding more and more issues and projects.

**Comment by nate-double-u** [comment]
Not internal CNCF projects, I was thinking more along the lines of labels for “etcd” or “Notary Project”

(Though, internal project labels could be useful too)

**Comment by celestehorgan** [comment]
@nate-double-u There are 108 projects and counting. It's a good idea but I'm not sure it's actually practical, given that we work on as many projects as we actually have headcount for.

**Comment by nate-double-u** [comment]
> @nate-double-u There are 108 projects and counting. It's a good idea but I'm not sure it's actually practical, given that we work on as many projects as we actually have headcount for.

I agree, labeling all 108 would be a bit much... maybe just the ones we're actively working on?

**Comment by nate-double-u** [comment]
closing as stale.
