### ISSUE TITLE
CNCFSD-1008 Docs assessment for KEDA

### ISSUE THREAD

**Issue by nate-double-u** [cncf/techdocs#87]
As per discussions around [CNCFSD-1008](https://cncfservicedesk.atlassian.net/browse/CNCFSD-1008?atlOrigin=eyJpIjoiZWE2YjRhNDc0OGJjNDkxMjhlNDUzNzg0YmM5ZThiZGUiLCJwIjoiaiJ9), let's do a Docs Assessment to help KEDA with their [website improvement project](https://github.com/kedacore/keda-docs/milestone/1).

**Comment by tomkerkhove** [comment]
Relates to https://github.com/kedacore/governance/issues/40

**Comment by nate-double-u** [comment]
[Draft Keda docs assessment](https://hackmd.io/@cncf-tech-docs/Bk_Y-ltt9)

**Comment by tomkerkhove** [comment]
Adding @zroubalik who has ideas to improve our docs as well.

**Comment by nate-double-u** [comment]
Hi @@zroubalik, please let me know if you're not able to access the doc. I think it's set up so that signed in users can edit. (trusting security through obscurity -- if an open link becomes problematic for this draft we can change the permissions)

**Comment by zroubalik** [comment]
@nate-double-u I am able to access the doc, thanks!

What I would like to see is to change KEDA documentation https://keda.sh/docs/2.7/ to something like https://docs.keda.sh - ie basically to have a project landing page on as it is now, but to have separate page for docs. Something like https://dapr.io/ and https://docs.dapr.io/, where:
- the left hand side menu has layout similar to what we can see on Dapr docs
- where we can easily see the current docs version (and have a way how to easily switch it)

**Comment by tomkerkhove** [comment]
I love that idea

**Comment by thisisobate** [comment]
Sounds good to me. This would warrant creating a more detailed information on the docs' landing page since the current one looks scanty.

Regardless, will discuss more with @nate-double-u about this. 
Thanks for the suggestion @zroubalik!

**Comment by nate-double-u** [comment]
Updated docs analysis PR: https://github.com/cncf/techdocs/pull/215
